name: df_config_example
homepage: https://dev-cetera.com/
repository: https://github.com/robmllze/df_config
funding:
- https://www.buymeacoffee.com/dev_cetera
- https://www.patreon.com/c/RobertMollentze
- https://github.com/sponsors/robmllze
publish_to: none
environment:
  sdk: ">=3.5.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  df_config:
    path: ../
dev_dependencies:
  lints: ^6.0.0

