//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY DF GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/df_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// --- PUBLIC FILES ---
export 'managers/config_manager.dart';
export 'managers/file_config_manager.dart';
export 'managers/translation_manager.dart';
export 'utils/replace_data.dart';
export 'utils/config_file_type.dart';
export 'utils/recursive_replace.dart';
export 'utils/replace_patterns.dart';
export 'utils/src_to_data.dart';
export 'utils/parse_source_for_strings_and_comments.dart';
export 'utils/extract_scopes.dart';
export 'utils/translation_file_reader.dart';
export 'extensions/tr_on_string_extension.dart';
export 'extensions/cf_on_string_extension.dart';
export 'configs/file_config.dart';
export 'configs/config.dart';
export 'refs/config_ref.dart';
export 'refs/locale_ref.dart';
export 'refs/config_file_ref.dart';

// --- PRIVATE FILES (EXCLUDED) ---
// None found.

// --- GENERATED FILES (EXCLUDED) ---
// export '_index.g.dart';